name: Gui V2

# Triggered after a branch is created, a tag or a branch is pushed or a PR with changes in
on:
  create:
  push:
  pull_request:

jobs:
  unit-tests:
    name: Unit Tests
    # If the commit message contains 'ci skip', it is not necessary to run this job
    if: contains(github.event.head_commit.message, 'ci skip') == false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:

    - name: checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: yarn install, build, lint and test
      run: |
        yarn install
        yarn run build
        yarn run lint
        yarn run test